import random
from typing import List, Dict, Any
from sqlalchemy.orm import Session
from models.database import UserAssignment, UserSkill

# Simulated Assignment Database
# In a real app, these could be generated by an LLM or pulled from a curated project bank.
SKILL_ASSIGNMENTS = {
    "python": [
        {"title": "Data Scraper", "description": "Build a Python script to scrape news headlines from a website and save them to a CSV file."},
        {"title": "File Organizer", "description": "Create a utility that moves files from your Downloads folder into subfolders based on file extension."},
        {"title": "API Wrapper", "description": "Write a Python class that interacts with the GitHub API to list a user's repositories."}
    ],
    "javascript": [
        {"title": "Interactive Quiz", "description": "Build a multi-question quiz using vanilla JS that tracks the user's score."},
        {"title": "Weather App", "description": "Create a simple dashboard that displays weather data from an API (e.g., OpenWeatherMap)."},
        {"title": "Task Manager", "description": "Implement a Todo list with local storage persistence."}
    ],
    "react": [
        {"title": "Portfolio Site", "description": "Create a responsive developer portfolio using React components."},
        {"title": "Social Dashboard", "description": "Build a UI for a social media dashboard with mock statistics and charts."},
        {"title": "E-commerce Gallery", "description": "Implement a product listing page with filtering and search capabilities."}
    ],
    "html": [
        {"title": "Semantic Landing Page", "description": "Design a clean landing page using semantic HTML5 elements (header, footer, section, etc.)."},
        {"title": "Registration Form", "description": "Build a complex user registration form with validation using only HTML attributes."}
    ],
    "sql": [
        {"title": "Library Schema", "description": "Design a database schema for a library system including books, authors, and loans."},
        {"title": "Reporting Queries", "description": "Write a set of SQL queries to calculate monthly sales growth from an orders table."}
    ]
}

def generate_assignment_for_user(db: Session, user_id: int, skills: List[str]) -> UserAssignment:
    """
    Selects a relevant assignment based on the user's skills and records it in the database.
    Prioritizes skills the user has but hasn't completed an assignment for.
    """
    if not skills:
        return None
        
    # Filter assignments for skills the user has
    available_assignments = []
    for skill in skills:
        skill_clean = skill.lower()
        if skill_clean in SKILL_ASSIGNMENTS:
            for assignment_data in SKILL_ASSIGNMENTS[skill_clean]:
                # Check if user already has this specific assignment
                exists = db.query(UserAssignment).filter(
                    UserAssignment.user_id == user_id,
                    UserAssignment.title == assignment_data["title"]
                ).first()
                
                if not exists:
                    available_assignments.append((skill_clean, assignment_data))
                    
    if not available_assignments:
        # Fallback: Pick any skill the user has and generate a generic project if no specific ones left
        chosen_skill = random.choice(skills)
        assignment_data = {
            "title": f"{chosen_skill.title()} Mini Project",
            "description": f"Design and implement a small application that demonstrates your core competence in {chosen_skill}."
        }
    else:
        # Pick a random one from available
        chosen_skill, assignment_data = random.choice(available_assignments)
        
    # Record and return
    new_assignment = UserAssignment(
        user_id=user_id,
        skill_name=chosen_skill,
        title=assignment_data["title"],
        description=assignment_data["description"],
        xp_reward=500
    )
    db.add(new_assignment)
    db.commit()
    db.refresh(new_assignment)
    return new_assignment

def get_user_assignments(db: Session, user_id: int) -> List[UserAssignment]:
    """Retrieves all assignments for a given user."""
    return db.query(UserAssignment).filter(UserAssignment.user_id == user_id).all()
